"""Add cascade deletes to foreign keys

Revision ID: 0ea10184559f
Revises: 37cc41b977f8
Create Date: 2025-07-25 21:26:38.091705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ea10184559f'
down_revision: Union[str, Sequence[str], None] = '37cc41b977f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('business_owners_ibfk_1'), 'business_owners', type_='foreignkey')
    op.create_foreign_key(None, 'business_owners', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('job_applications_ibfk_2'), 'job_applications', type_='foreignkey')
    op.drop_constraint(op.f('job_applications_ibfk_1'), 'job_applications', type_='foreignkey')
    op.create_foreign_key(None, 'job_applications', 'jobs', ['job_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'job_applications', 'workers', ['worker_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('jobs_ibfk_1'), 'jobs', type_='foreignkey')
    op.create_foreign_key(None, 'jobs', 'business_owners', ['business_owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('workers_ibfk_1'), 'workers', type_='foreignkey')
    op.create_foreign_key(None, 'workers', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'workers', type_='foreignkey')
    op.create_foreign_key(op.f('workers_ibfk_1'), 'workers', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'jobs', type_='foreignkey')
    op.create_foreign_key(op.f('jobs_ibfk_1'), 'jobs', 'business_owners', ['business_owner_id'], ['id'])
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    op.drop_constraint(None, 'job_applications', type_='foreignkey')
    op.create_foreign_key(op.f('job_applications_ibfk_1'), 'job_applications', 'jobs', ['job_id'], ['id'])
    op.create_foreign_key(op.f('job_applications_ibfk_2'), 'job_applications', 'workers', ['worker_id'], ['id'])
    op.drop_constraint(None, 'business_owners', type_='foreignkey')
    op.create_foreign_key(op.f('business_owners_ibfk_1'), 'business_owners', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
