"""add fcm_token to worker

Revision ID: 11f2940311dc
Revises: 1ed96c5aab18
Create Date: 2025-07-22 00:27:02.358080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11f2940311dc'
down_revision: Union[str, Sequence[str], None] = '1ed96c5aab18'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('workers', sa.Column('fcm_token', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'fcm_token')
    # ### end Alembic commands ###
