"""add latitude and longitude to job and worker

Revision ID: 1ed96c5aab18
Revises: 
Create Date: 2025-07-16 21:09:36.041557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ed96c5aab18'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('jobs', sa.Column('longitude', sa.Float(), nullable=True))
    op.add_column('workers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('workers', sa.Column('longitude', sa.Float(), nullable=True))
    op.create_table(
        'notifications',
        sa.Column('id', sa.Integer(), primary_key=True, index=True),
        sa.Column('worker_id', sa.Integer(), sa.ForeignKey('workers.id'), nullable=False),
        sa.Column('job_id', sa.Integer(), sa.ForeignKey('jobs.id'), nullable=False),
        sa.Column('message', sa.String(), nullable=False),
        sa.Column('is_read', sa.Boolean(), default=False),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('workers', 'longitude')
    op.drop_column('workers', 'latitude')
    op.drop_column('jobs', 'longitude')
    op.drop_column('jobs', 'latitude')
    op.drop_table('notifications')
    # ### end Alembic commands ###
