"""add fcm_token to business_owners

Revision ID: fee64ff8095e
Revises: 0ea10184559f
Create Date: 2025-07-27 23:26:39.559776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fee64ff8095e'
down_revision: Union[str, Sequence[str], None] = '0ea10184559f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('business_owners', sa.Column('fcm_token', sa.String(length=255), nullable=True))
    op.create_unique_constraint('unique_job_worker_application', 'job_applications', ['job_id', 'worker_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_job_worker_application', 'job_applications', type_='unique')
    op.drop_column('business_owners', 'fcm_token')
    # ### end Alembic commands ###
