name: Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r workbee-Back/requirements.txt

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan ${{ secrets.VM_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to VM
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} '
            cd /path/to/your/app &&
            git pull origin main &&
            source venv/bin/activate &&
            pip install -r requirements.txt &&
            sudo systemctl restart your-app-service
          '
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock

# Replace /path/to/your/app, your-app-service, and ensure VM_USER and VM_HOST secrets are set in GitHub. 