name: Build and Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker

    - name: Build and push Docker image
      run: |
        IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/workbee-repo/workbee-backend:${{ github.sha }}"
        gcloud artifacts repositories create workbee-repo --repository-format=docker --location=us-central1 || true
        docker build -t $IMAGE .
        docker push $IMAGE

    - name: Deploy to Cloud Run
      run: |
        IMAGE="us-central1-docker.pkg.dev/${{ secrets.GCP_PROJECT_ID }}/workbee-repo/workbee-backend:${{ github.sha }}"
        gcloud run deploy workbee-backend \
          --image $IMAGE \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated \
          --port 8080

# Replace /path/to/your/app, your-app-service, and ensure VM_USER and VM_HOST secrets are set in GitHub. 